[project]
name = "buildcheck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "reflex>=0.8.0",
    "supabase>=2.16.0",
    "reflex-enterprise>=0.3.0",

]
